unstable_features = true

brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysSameLine"

imports_granularity = "Module"
group_imports = "StdExternalCrate"

use_field_init_shorthand = true
skip_macro_invocations = ["*"]

comment_width = 115
wrap_comments = true

max_width = 115
array_width = 100
chain_width = 60
single_line_if_else_max_width = 50
single_line_let_else_max_width = 115
struct_lit_width = 60
struct_variant_width = 60
